This document is a follow along guide for a Kaggle tutorial on NumPy. 

The topics covered are as follows:

1. ndarray
2. Create a specific array
3. Shape and operation
4. Index
5. Mathematics
6. Matrix
7. Random Number


In [2]:
# In order to operate NumPy with Jupyter Notebooks, you must first import the package
import numpy as np
#Also import Pandas, for data processing purposes
import pandas as pd

##### 1. Creating two arrays with NumPy: 1 and 2 dimensional arrays

In [3]:
a = np.array([1, 2, 3])
b = np.array([(1, 2, 3),(4, 5, 6)])

print('a: ', a)
print('b: ', b)

a:  [1 2 3]
b:  [[1 2 3]
 [4 5 6]]


In [6]:
#Show arrays' dimension, shape, size, data type and itemsize.

print('a=')
print(a)
print("a's ndim {}".format(a.ndim))
print("a's shape {}".format(a.shape))
print("a's size {}".format(a.size))
print("a's dtype {}".format(a.dtype))
print("a's itemsize {}".format(a.itemsize))

print('')

print('b=')
print(b)
print("b's ndim {}".format(b.ndim))
print("b's shape {}".format(b.shape))
print("b's size {}".format(b.size))
print("b's dtype {}".format(b.dtype))
print("b's itemsize [] {}".format(b.itemsize))
print({{"Ricky's name is"}}.format())

a=
[[0. 0. 0.]
 [0. 0. 0.]]
a's ndim 2
a's shape (2, 3)
a's size 6
a's dtype float64
a's itemsize 8

b=
[[1. 1. 1.]
 [1. 1. 1.]]
b's ndim 2
b's shape (2, 3)
b's size 6
b's dtype float64
b's itemsize 8


In [11]:
#Trying the same without .format
a= np.array([(1,2,3,4), (4,5,6,7)])
print('a=')
print(a)
print('a ndim=', a.ndim)
print('a shape =', a.shape)
print('a size=', a.size)
print('a dtype=', a.dtype)
print('a itemsize=', a.itemsize)

a=
[[1 2 3 4]
 [4 5 6 7]]
a ndim= 2
a shape = (2, 4)
a size= 8
a dtype= int32
a itemsize= 4


2. Creating specific arrays: zeroes, ones, an empty array, an array with a range of numbers, an array that includes a linespace and an array filled with random numbers

In [5]:
# a = np.zeros((2,3))
# print('np.zeros((2,3)= \n{}\n'.format(a))

# b = np.ones((2,3))
# print('np.ones((2,3))= \n{}\n'.format(b))

c = np.empty((2,3))
print('np.empty((2,3))= \n{}\n'.format(c))

d = np.arange(1, 2, 0.3) - shift + tab
print('np.arange(1, 2, 0.3)= \n{}\n'.format(d))

e = np.linspace(1, 2, 7)
print('np.linspace(1, 2, 7)= \n{}\n'.format(e))

f = np.random.random((2,3))
print('np.random.random((2,3))= \n{}\n'.format(f))

np.empty((2,3))= 
[[0.75226374 0.40225435 0.47981695]
 [0.04331524 0.31846234 0.37087489]]

np.arange(1, 2, 0.3)= 
[1.  1.3 1.6 1.9]

np.linspace(1, 2, 7)= 
[1.         1.16666667 1.33333333 1.5        1.66666667 1.83333333
 2.        ]

np.random.random((2,3))= 
[[0.92072406 0.21848622 0.63678528]
 [0.52254171 0.49243312 0.18975186]]



In [22]:
#Without .format
a = np.zeros((2, 3))
print('a np.zeros\n', a)

b= np.arange(1,2,0.3)
print('b range\n', b)

e= np.linspace(10,20,12)
print('e linespace\n', e)

a np.zeros
 [[0. 0. 0.]
 [0. 0. 0.]]
b range
 [1.  1.3 1.6 1.9]
e linespace
 [10.         10.90909091 11.81818182 12.72727273 13.63636364 14.54545455
 15.45454545 16.36363636 17.27272727 18.18181818 19.09090909 20.        ]


3. Shape and operation of arrays - reshaping, vertical and horizontal stacking of multiple arrays and vertical and horizontal splitting of arrays

In [37]:
# Setting up arrays to modify
zeroes = np.zeros((2,6))
ones = np.ones((2,3))
onecol = np.random.random((12,1))

print(zeroes)
print(ones)
print(onecol)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[0.01351633]
 [0.96728699]
 [0.70531992]
 [0.55125873]
 [0.08336559]
 [0.4826359 ]
 [0.31785339]
 [0.53100824]
 [0.05585257]
 [0.23703002]
 [0.77169658]
 [0.3959486 ]]


In [41]:
# Reshaping arrays
ones = ones.reshape(6,1)
print(ones)
ones = ones.reshape(1,6)
print(ones)

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]
[[1. 1. 1. 1. 1. 1.]]


In [38]:
# Preparing arrays to stack
onecol = onecol.reshape(2,6)
print(onecol)

[[0.01351633 0.96728699 0.70531992 0.55125873 0.08336559 0.4826359 ]
 [0.31785339 0.53100824 0.05585257 0.23703002 0.77169658 0.3959486 ]]


In [42]:
# Stacking available arrays vertically
v_stack = np.vstack((zeroes, ones, onecol))
print(v_stack)

[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.        ]
 [1.         1.         1.         1.         1.         1.        ]
 [0.01351633 0.96728699 0.70531992 0.55125873 0.08336559 0.4826359 ]
 [0.31785339 0.53100824 0.05585257 0.23703002 0.77169658 0.3959486 ]]


In [46]:
# Preparing ones array to stack horizontally
ones = ones.reshape(2,3)

In [47]:
# Stacking arrays horizontally
h_stack = np.hstack((zeroes, ones, onecol))
print(h_stack)

[[0.         0.         0.         0.         0.         0.
  1.         1.         1.         0.01351633 0.96728699 0.70531992
  0.55125873 0.08336559 0.4826359 ]
 [0.         0.         0.         0.         0.         0.
  1.         1.         1.         0.31785339 0.53100824 0.05585257
  0.23703002 0.77169658 0.3959486 ]]


In [49]:
# Testing formatting/readability with 2x6 array of ones.
ones = np.ones((2,6))
h_stack = np.hstack((zeroes, ones, onecol))
print(h_stack)

[[0.         0.         0.         0.         0.         0.
  1.         1.         1.         1.         1.         1.
  0.01351633 0.96728699 0.70531992 0.55125873 0.08336559 0.4826359 ]
 [0.         0.         0.         0.         0.         0.
  1.         1.         1.         1.         1.         1.
  0.31785339 0.53100824 0.05585257 0.23703002 0.77169658 0.3959486 ]]


In [53]:
# Trying again because I don't know why it splits the arrays this way
ones = ones.reshape((6,2))
zeroes = zeroes.reshape((6,2))
onecol = onecol.reshape((6,2))
print(ones)
print(zeroes)
print(onecol)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[[0.01351633 0.96728699]
 [0.70531992 0.55125873]
 [0.08336559 0.4826359 ]
 [0.31785339 0.53100824]
 [0.05585257 0.23703002]
 [0.77169658 0.3959486 ]]


In [56]:
h_stack = np.hstack((zeroes, ones, onecol))
print(h_stack)

[[0.         0.         1.         1.         0.01351633 0.96728699]
 [0.         0.         1.         1.         0.70531992 0.55125873]
 [0.         0.         1.         1.         0.08336559 0.4826359 ]
 [0.         0.         1.         1.         0.31785339 0.53100824]
 [0.         0.         1.         1.         0.05585257 0.23703002]
 [0.         0.         1.         1.         0.77169658 0.3959486 ]]


In [71]:
# Splitting arrays vertically
h_split = np. hsplit(h_stack, 3)
print(h_split)

[array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]]), array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]]), array([[0.01351633, 0.96728699],
       [0.70531992, 0.55125873],
       [0.08336559, 0.4826359 ],
       [0.31785339, 0.53100824],
       [0.05585257, 0.23703002],
       [0.77169658, 0.3959486 ]])]


In [72]:
print(h_split[1])

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [66]:
print(h_stack)

[[0.         0.         1.         1.         0.01351633 0.96728699]
 [0.         0.         1.         1.         0.70531992 0.55125873]
 [0.         0.         1.         1.         0.08336559 0.4826359 ]
 [0.         0.         1.         1.         0.31785339 0.53100824]
 [0.         0.         1.         1.         0.05585257 0.23703002]
 [0.         0.         1.         1.         0.77169658 0.3959486 ]]


In [73]:
h_split = np.hsplit(h_stack, 2)
print(h_split)

[array([[0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.]]), array([[1.        , 0.01351633, 0.96728699],
       [1.        , 0.70531992, 0.55125873],
       [1.        , 0.08336559, 0.4826359 ],
       [1.        , 0.31785339, 0.53100824],
       [1.        , 0.05585257, 0.23703002],
       [1.        , 0.77169658, 0.3959486 ]])]


In [74]:
print(h_split[0])

[[0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]]


In [75]:
print(h_split[1])

[[1.         0.01351633 0.96728699]
 [1.         0.70531992 0.55125873]
 [1.         0.08336559 0.4826359 ]
 [1.         0.31785339 0.53100824]
 [1.         0.05585257 0.23703002]
 [1.         0.77169658 0.3959486 ]]


4. Indexing of NumPy arrays

In [7]:
# Setting up array
base_data = np.arange(100, 200)
print(base_data)

[100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153
 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171
 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189
 190 191 192 193 194 195 196 197 198 199]


In [8]:
# selecting every 10 value from base_data within <60
every_10 = np.arange(0, 60, 10)
print(base_data[every_10])

[100 110 120 130 140 150]


In [9]:
# Selecting specific values as an array within the given array
a = np.array([(5,10), (80, 90)])
print(a)

[[ 5 10]
 [80 90]]


In [10]:
print(base_data[a])

[[105 110]
 [180 190]]


In [11]:
# Reshaping data into a 10x10 array
box_data = base_data.reshape((12, -1))
print(box_data)

ValueError: cannot reshape array of size 100 into shape (12,newaxis)

In [92]:
# Selecting specific rows, columns from array
print(box_data[0])

[100 101 102 103 104 105 106 107 108 109]


In [93]:
# Specific value located at index 0,0
print(box_data[0, 0])

100


In [94]:
print(box_data[0, :])

[100 101 102 103 104 105 106 107 108 109]


In [95]:
# All values in one column
print(box_data[:, -1])

[109 119 129 139 149 159 169 179 189 199]


In [96]:
# Selecting a specific array within data - first 6 rows, first 8 columns.
print(box_data[0:6, 0:8])

[[100 101 102 103 104 105 106 107]
 [110 111 112 113 114 115 116 117]
 [120 121 122 123 124 125 126 127]
 [130 131 132 133 134 135 136 137]
 [140 141 142 143 144 145 146 147]
 [150 151 152 153 154 155 156 157]]


In [97]:
# Last 5 rows, last 2 columns
print(box_data[5:, 8:])

[[158 159]
 [168 169]
 [178 179]
 [188 189]
 [198 199]]


5. NumPy Mathematics

In [101]:
# Show calculations on array
print(np.amin(box_data))
print(np.amax(box_data))
print(np.average(box_data))
print(np.sum(box_data))
print(np.sin(box_data))

100
199
149.5
14950
[[-0.50636564  0.45202579  0.99482679  0.62298863 -0.3216224  -0.97053528
  -0.7271425   0.18478174  0.92681851  0.81674261]
 [-0.04424268 -0.86455145 -0.8899956  -0.09718191  0.78498039  0.94543533
   0.23666139 -0.68969794 -0.98195217 -0.3714041 ]
 [ 0.58061118  0.99881522  0.49871315 -0.45990349 -0.99568699 -0.61604046
   0.32999083  0.97263007  0.72103771 -0.19347339]
 [-0.93010595 -0.81160339  0.05308359  0.86896576  0.88592482  0.08836869
  -0.79043321 -0.94251445 -0.22805226  0.69608013]
 [ 0.98023966  0.36317137 -0.58779501 -0.99834536 -0.49102159  0.46774516
   0.99646917  0.60904402 -0.33833339 -0.97464865]
 [-0.71487643  0.20214988  0.93332052  0.80640058 -0.06192034 -0.87331198
  -0.88178462 -0.07954854  0.7958241   0.93951973]
 [ 0.21942526 -0.70240779 -0.97845035 -0.35491018  0.59493278  0.99779728
   0.48329156 -0.47555019 -0.99717329 -0.60199987]
 [ 0.34664946  0.97659087  0.70865914 -0.21081053 -0.93646197 -0.8011346
   0.07075224  0.87758979  0.877

In [102]:
# Using operators on an array
print(box_data * box_data)

[[10000 10201 10404 10609 10816 11025 11236 11449 11664 11881]
 [12100 12321 12544 12769 12996 13225 13456 13689 13924 14161]
 [14400 14641 14884 15129 15376 15625 15876 16129 16384 16641]
 [16900 17161 17424 17689 17956 18225 18496 18769 19044 19321]
 [19600 19881 20164 20449 20736 21025 21316 21609 21904 22201]
 [22500 22801 23104 23409 23716 24025 24336 24649 24964 25281]
 [25600 25921 26244 26569 26896 27225 27556 27889 28224 28561]
 [28900 29241 29584 29929 30276 30625 30976 31329 31684 32041]
 [32400 32761 33124 33489 33856 34225 34596 34969 35344 35721]
 [36100 36481 36864 37249 37636 38025 38416 38809 39204 39601]]


In [103]:
print(box_data + box_data)

[[200 202 204 206 208 210 212 214 216 218]
 [220 222 224 226 228 230 232 234 236 238]
 [240 242 244 246 248 250 252 254 256 258]
 [260 262 264 266 268 270 272 274 276 278]
 [280 282 284 286 288 290 292 294 296 298]
 [300 302 304 306 308 310 312 314 316 318]
 [320 322 324 326 328 330 332 334 336 338]
 [340 342 344 346 348 350 352 354 356 358]
 [360 362 364 366 368 370 372 374 376 378]
 [380 382 384 386 388 390 392 394 396 398]]


In [104]:
print(box_data * 0.1)

[[10.  10.1 10.2 10.3 10.4 10.5 10.6 10.7 10.8 10.9]
 [11.  11.1 11.2 11.3 11.4 11.5 11.6 11.7 11.8 11.9]
 [12.  12.1 12.2 12.3 12.4 12.5 12.6 12.7 12.8 12.9]
 [13.  13.1 13.2 13.3 13.4 13.5 13.6 13.7 13.8 13.9]
 [14.  14.1 14.2 14.3 14.4 14.5 14.6 14.7 14.8 14.9]
 [15.  15.1 15.2 15.3 15.4 15.5 15.6 15.7 15.8 15.9]
 [16.  16.1 16.2 16.3 16.4 16.5 16.6 16.7 16.8 16.9]
 [17.  17.1 17.2 17.3 17.4 17.5 17.6 17.7 17.8 17.9]
 [18.  18.1 18.2 18.3 18.4 18.5 18.6 18.7 18.8 18.9]
 [19.  19.1 19.2 19.3 19.4 19.5 19.6 19.7 19.8 19.9]]


In [105]:
print(box_data + (10*5))

[[150 151 152 153 154 155 156 157 158 159]
 [160 161 162 163 164 165 166 167 168 169]
 [170 171 172 173 174 175 176 177 178 179]
 [180 181 182 183 184 185 186 187 188 189]
 [190 191 192 193 194 195 196 197 198 199]
 [200 201 202 203 204 205 206 207 208 209]
 [210 211 212 213 214 215 216 217 218 219]
 [220 221 222 223 224 225 226 227 228 229]
 [230 231 232 233 234 235 236 237 238 239]
 [240 241 242 243 244 245 246 247 248 249]]


In [106]:
print(np.sqrt(box_data))

[[10.         10.04987562 10.09950494 10.14889157 10.19803903 10.24695077
  10.29563014 10.34408043 10.39230485 10.44030651]
 [10.48808848 10.53565375 10.58300524 10.63014581 10.67707825 10.72380529
  10.77032961 10.81665383 10.86278049 10.90871211]
 [10.95445115 11.         11.04536102 11.09053651 11.13552873 11.18033989
  11.22497216 11.26942767 11.3137085  11.35781669]
 [11.40175425 11.44552314 11.48912529 11.53256259 11.5758369  11.61895004
  11.66190379 11.70469991 11.74734012 11.78982612]
 [11.83215957 11.87434209 11.91637529 11.95826074 12.         12.04159458
  12.08304597 12.12435565 12.16552506 12.20655562]
 [12.24744871 12.28820573 12.32882801 12.36931688 12.40967365 12.4498996
  12.489996   12.52996409 12.56980509 12.60952021]
 [12.64911064 12.68857754 12.72792206 12.76714533 12.80624847 12.84523258
  12.88409873 12.92284798 12.9614814  13.        ]
 [13.03840481 13.07669683 13.11487705 13.15294644 13.19090596 13.22875656
  13.26649916 13.3041347  13.34166406 13.37908816]
 

In [107]:
# Standard deviation of the first row of values
print(np.std(box_data[0]))

2.8722813232690143


In [108]:
print(np.std(box_data))

28.86607004772212


In [109]:
# Sum of the second row
print(np.sum(box_data[1]))

1145


In [110]:
# Average of one row
print(np.average(box_data[3]))

134.5


6. Numpy Matrices

In [120]:
# Setting up a matrix to work with
grid = np.random.random(25)
print(grid)

[0.6096429  0.76816229 0.59162185 0.16406907 0.21560495 0.84922835
 0.98654545 0.93629676 0.79556392 0.60712494 0.7694131  0.16421135
 0.09709149 0.02285499 0.39359319 0.79651564 0.05546608 0.39744825
 0.94552526 0.97920424 0.34861916 0.25281995 0.78868357 0.64117896
 0.83840095]


In [121]:
grid5 = grid.reshape(5, 5)

In [122]:
print(grid5)

[[0.6096429  0.76816229 0.59162185 0.16406907 0.21560495]
 [0.84922835 0.98654545 0.93629676 0.79556392 0.60712494]
 [0.7694131  0.16421135 0.09709149 0.02285499 0.39359319]
 [0.79651564 0.05546608 0.39744825 0.94552526 0.97920424]
 [0.34861916 0.25281995 0.78868357 0.64117896 0.83840095]]


In [124]:
# Tranpose grid
print(grid5.transpose())

[[0.6096429  0.84922835 0.7694131  0.79651564 0.34861916]
 [0.76816229 0.98654545 0.16421135 0.05546608 0.25281995]
 [0.59162185 0.93629676 0.09709149 0.39744825 0.78868357]
 [0.16406907 0.79556392 0.02285499 0.94552526 0.64117896]
 [0.21560495 0.60712494 0.39359319 0.97920424 0.83840095]]


In [127]:
grid_ones = np.ones((5,5))
print(grid_ones)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [129]:
twos = grid_ones * 2
print(twos)

[[2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]]


In [130]:
# Matrix mupltiplication using the .dot function
print(np.dot(grid5, twos))

[[4.69820211 4.69820211 4.69820211 4.69820211 4.69820211]
 [8.34951886 8.34951886 8.34951886 8.34951886 8.34951886]
 [2.89432824 2.89432824 2.89432824 2.89432824 2.89432824]
 [6.34831893 6.34831893 6.34831893 6.34831893 6.34831893]
 [5.73940516 5.73940516 5.73940516 5.73940516 5.73940516]]
