<div>
<img src=https://www.institutedata.com/wp-content/uploads/2019/10/iod_h_tp_primary_c.svg width="300">
</div>

# Lab 4.1.2 Linear Regression

## Prediction of House Price Using Linear Regression

### Data

The Sacramento real estate transactions file is a list of 985 real estate transactions in the Sacramento area reported over a five-day period, as reported by the Sacramento Bee.

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

### 1. Explore Data

Perform EDA on this dataset. Find Dependent and Independent Variables to predict house price.

In [3]:
# Read CSV
house_csv = pd.read_csv("Sacramento_transactions.csv")

In [4]:
house_csv.head()

street        city    zip state  beds  baths  sq__ft  \
0      3526 HIGH ST  SACRAMENTO  95838    CA     2      1     836   
1       51 OMAHA CT  SACRAMENTO  95823    CA     3      1    1167   
2    2796 BRANCH ST  SACRAMENTO  95815    CA     2      1     796   
3  2805 JANETTE WAY  SACRAMENTO  95815    CA     2      1     852   
4   6001 MCMAHON DR  SACRAMENTO  95824    CA     2      1     797   

          type                     sale_date  price   latitude   longitude  
0  Residential  Wed May 21 00:00:00 EDT 2008  59222  38.631913 -121.434879  
1  Residential  Wed May 21 00:00:00 EDT 2008  68212  38.478902 -121.431028  
2  Residential  Wed May 21 00:00:00 EDT 2008  68880  38.618305 -121.443839  
3  Residential  Wed May 21 00:00:00 EDT 2008  69307  38.616835 -121.439146  
4  Residential  Wed May 21 00:00:00 EDT 2008  81900  38.519470 -121.435768

### 2. Predict Price

We are going to predict `price` from available information.

#### 2.1 What is the Target Variable? Why?

In [5]:
# ANSWER
y = house_csv['price']

#### 2.2 List all possible variables which might be Independent/Predictor variable.

In [6]:
# ANSWER
X = house_csv['sq__ft']

#### 2.3 Find correlation between variables

Find correlation between variables. Which is the best predictor? Why? State your reason.

In [7]:
# ANSWER
house_csv.corr()

zip      beds     baths    sq__ft     price  latitude  \
zip        1.000000  0.125319  0.069165  0.130108 -0.093353 -0.290389   
beds       0.125319  1.000000  0.839650  0.684041  0.342024 -0.291307   
baths      0.069165  0.839650  1.000000  0.665690  0.416208 -0.235792   
sq__ft     0.130108  0.684041  0.665690  1.000000  0.333897 -0.383274   
price     -0.093353  0.342024  0.416208  0.333897  1.000000 -0.039573   
latitude  -0.290389 -0.291307 -0.235792 -0.383274 -0.039573  1.000000   
longitude -0.539904 -0.053993  0.016582 -0.177742  0.284485  0.387925   

           longitude  
zip        -0.539904  
beds       -0.053993  
baths       0.016582  
sq__ft     -0.177742  
price       0.284485  
latitude    0.387925  
longitude   1.000000

#### 2.4 Find Coefficient and Intercept using Linear Regression

Using LinearRegression of sklearn.linear_model package find Coefficient and Intercept.

Create an instance of LinearRegression.

Explore following methods:

- fit
- predict
- score

In [8]:
from sklearn.linear_model import LinearRegression

In [9]:
model = LinearRegression()

In [11]:
X = house_csv['sq__ft']
Y = house_csv['price']

print(X.shape)
print(Y.shape)

(985,)
(985,)


##### 2.4.1 Fit predictor and target variables using linear regression 

In [12]:
# ANSWER

X = house_csv['sq__ft'].values.reshape(-1,1)
y = house_csv['price'].values.reshape(-1,1)

linreg = LinearRegression()
linreg.fit(X, Y)

print(linreg.coef_, linreg.intercept_)
print(X.shape)
print(y.shape)

[54.15863969] 162930.16140699777
(985, 1)
(985, 1)


##### 2.4.2 Find R Score

Find $R^2$ Using ```score``` method of Linear Regression.

In [13]:
# ANSWER
linreg.score(X, y)


0.11148717682951437

### 3. Splitting Data

In [14]:
from sklearn.model_selection import train_test_split

#### 3.1 Create training and testing subsets

Hint: Using `train_test_split` Library.

```
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)
```

In [15]:
# ANSWER
## Create training and testing subsets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.33, random_state=42)

#### 3.2 Check Shape, Sample of Test Train Data

In [17]:
# ANSWER
## Check training/test data
print(len(X_train), len(X_test), len(y_train), len(y_test))
print(X_train.shape, y_train.shape, X_test.shape, y_test.shape)

659 326 659 326
(659, 1) (659, 1) (326, 1) (326, 1)


#### 3.3 Using Linear Regression Find The Score

1. Fit model using X_train, y_train
2. Find score using X_test, y_test

In [18]:
# ANSWER
linreg.fit(X_train, y_train)
print(linreg.coef_, linreg.intercept_)

[[47.43508406]] [166482.34144969]


In [19]:
# ANSWER
linreg.score(X_test, y_test)

0.13602012247180006

### 4. Predict House Price

Let's assume we have information of following house:

- street:	1140 EDMONTON DR
- city:	SACRAMENTO
- zip:	95833
- state:	CA
- beds:	3
- baths:	2
- sq__ft:	1204
- type:	Residential

**Predict the price of this house using linear regression model.**

In [20]:
# ANSWER
linreg.predict(X)

array([[206138.07172793],
       [221839.08455341],
       [204240.66836534],
       [206897.03307297],
       [204288.1034494 ],
       [219704.50577049],
       [218850.67425732],
       [222313.43539406],
       [211118.75555474],
       [220842.94778804],
       [209600.83286467],
       [227626.16480932],
       [207798.2996702 ],
       [214866.12719587],
       [214960.997364  ],
       [220273.72677927],
       [206517.55240045],
       [204193.23328127],
       [194374.17087984],
       [230804.31544167],
       [219514.76543423],
       [229523.56817192],
       [225301.84569014],
       [242425.91103757],
       [209221.35219215],
       [218091.71291228],
       [212162.32740417],
       [219562.20051829],
       [231942.75745923],
       [225681.32636266],
       [215767.3937931 ],
       [221127.55829243],
       [231942.75745923],
       [219419.8952661 ],
       [215767.3937931 ],
       [233745.29065369],
       [217807.10240789],
       [236306.7851932 ],
       [2208

In [24]:
def create_price_estimate(x):
    
    beta_0 = linreg.intercept_
    beta_1 = linreg.coef_
    
    estimate = beta_0 + (beta_1 * x)
    
    return estimate

In [25]:
create_price_estimate(1204)

array([[223594.18266381]])

#### Find the error

In [30]:
from sklearn import metrics

In [31]:
# Predict price from X_test
y_pred = linreg.predict(X_test)
y_pred

array([[209458.52761247],
       [279472.71169224],
       [259549.97638499],
       [248971.95263852],
       [238915.71481676],
       [166482.34144969],
       [166482.34144969],
       [256609.00117297],
       [166482.34144969],
       [166482.34144969],
       [217807.10240789],
       [166482.34144969],
       [220558.33728366],
       [166482.34144969],
       [219040.41459358],
       [241714.38477659],
       [204193.23328127],
       [204240.66836534],
       [166482.34144969],
       [309214.50940092],
       [253288.54528842],
       [231088.92594606],
       [277195.82765713],
       [226487.72279177],
       [222171.13014186],
       [243516.91797106],
       [258506.40453556],
       [218660.93392106],
       [242188.73561724],
       [253668.02596094],
       [226677.46312803],
       [254284.68205379],
       [237872.14296734],
       [238678.53939644],
       [166482.34144969],
       [222171.13014186],
       [206138.07172793],
       [242425.91103757],
       [2157

In [32]:
print("Mean Absolute Error: ", metrics.mean_absolute_error(y_test, y_pred))


Mean Absolute Error:  100799.98255883317


In [33]:
from sklearn.metrics import mean_squared_error

In [34]:
len(y_pred)

326

In [40]:
print("Mean Squared Error: ", metrics.mean_squared_error(y_test[:100], y_pred[:100], squared=True))

Mean Squared Error:  14875597543.998333




---



---



> > > > > > > > > © 2019 Institute of Data


---



---



